image: node:boron

before_script:
- npm install -g gulp-cli bower
- npm install
- bower install --allow-root

cache:
  paths:
  - node_modules

pages:
  script:
  - gulp build
  artifacts:
    paths:
    - public
  only:
  - master
